### ISSUE TITLE
Breadcrumbs in knp

### ISSUE THREAD

**Issue by Migo2468** [kevinpapst/AdminLTEBundle#44]
Hi, how can I enabled breadcrumbs in knp menu. 

Now I have `KnpMenuBuilderListener` but when I enabled bradcrumbs in admin_lte.yaml it has no effect.

**Comment by robertosanval** [comment]
Same problem here :(

**Comment by kevinpapst** [comment]
Sorry guys, I don't use KnpMenu and it looks as if there was a bug.
Can you check the attached PR and see if that fixes the problem for you?
I also updated the documentation to be clearer how to use the breadcrumb with KnpMenu.

**Comment by Migo2468** [comment]
Thx, my problem is solved by this fix

**Comment by Migo2468** [comment]
Hi, 

One question more. In clasic menu You have 2 Events: 
- THEME_SIDEBAR_SETUP_MENU - this show menu in sidebar
- THEME_BREADCRUMB - this is used to breadcrumbs

Here I can show only 1 and 2 level in menu but I can show in breadcrumbs more details menu. 

In KNP I don't see similar event to THEME_BREADCRUMB. 

I find only THEME_SIDEBAR_SETUP_KNP_MENU. 
It is posible to show another menu to breadcrumbs ?

**Comment by kevinpapst** [comment]
Yes, as written in the documentation:
https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/knp_menu.md#enabling-breadcrumb-support

You can add your own MenuBuilder and configure its alias instead of setting the breadcrumbs to `true`, see this config defining the adminlte_main Builder:
https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/config/container/knp-menu.yml

 Or you simply overwrite the knp menu partial:
https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/views/Breadcrumb/knp-breadcrumb.html.twig

**Comment by robertosanval** [comment]
The problem is solved for me too. Thanks!
